# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# To specify which agents are active by default when --agents is not used,
# uncomment and populate the following line. If omitted, all agents are active.
default_agents = ["cursor", "claude"]

# Enable nested rule loading from nested .ruler directories
# When enabled, ruler will search for and process .ruler directories throughout the project hierarchy
# nested = false

# --- Agent Specific Configurations ---

[agents.claude]
enabled = true
output_path = "CLAUDE.md"

# OpenAI Codex CLI agent and MCP config
[agents.codex]
enabled = true
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

[agents.gemini-cli]
enabled = true

# --- Global MCP Server Configuration ---
#[mcp]
# Enable/disable MCP propagation globally (default: true)
#enabled = true
# Global merge strategy: 'merge' or 'overwrite' (default: 'merge')
#merge_strategy = "merge"


# --- MCP Servers ---
[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/project"]

#[mcp_servers.remote_api]
#url = "https://api.example.com"

#[mcp_servers.remote_api.headers]
#Authorization = "Bearer your-token"

# --- Global .gitignore Configuration ---
[gitignore]
# Enable/disable automatic .gitignore updates (default: true)
enabled = true