// 백엔드 스키마를 프론트엔드에서 재사용하기 위한 DTO 재노출
export {
  CoursesQueryParamsSchema,
  CourseParamsSchema,
  EnrollmentStatusParamsSchema,
  CourseResponseSchema,
  CoursesResponseSchema,
  CourseDetailResponseSchema,
  EnrollmentStatusResponseSchema,
  // Course Management 관련 스키마들
  CreateCourseRequestSchema,
  UpdateCourseRequestSchema,
  CourseStatusUpdateSchema,
  InstructorCoursesQuerySchema,
  InstructorCourseResponseSchema,
  InstructorCoursesResponseSchema,
  type CoursesQueryParams,
  type CourseParams,
  type EnrollmentStatusParams,
  type CourseResponse,
  type CoursesResponse,
  type CourseDetailResponse,
  type EnrollmentStatusResponse,
  // Course Management 관련 타입들
  type CreateCourseRequest,
  type UpdateCourseRequest,
  type CourseStatusUpdate,
  type InstructorCoursesQuery,
  type InstructorCourseResponse,
  type InstructorCoursesResponse,
} from '@/features/courses/backend/schema';
